version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: clausewise_postgres
    environment:
      POSTGRES_DB: clausewise
      POSTGRES_USER: clausewise_user
      POSTGRES_PASSWORD: clausewise_secure_password
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    command: >
      postgres 
      -c ssl=on 
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem 
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
      -c shared_preload_libraries=pg_stat_statements
      -c log_statement=all
      -c log_min_duration_statement=0
    restart: unless-stopped
    networks:
      - clausewise_network

  redis-broker:
    image: redis:7-alpine
    container_name: clausewise_redis
    command: redis-server --appendonly yes --requirepass redis_secure_password
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - clausewise_network

  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clausewise_backend
    environment:
      DATABASE_URL: postgresql://clausewise_user:clausewise_secure_password@postgres-db:5432/clausewise
      REDIS_URL: redis://:redis_secure_password@redis-broker:6379/0
      SECRET_KEY: your-super-secret-jwt-key-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      ENVIRONMENT: production
    volumes:
      - ./backend:/app
      - document_uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - redis-broker
    restart: unless-stopped
    networks:
      - clausewise_network

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clausewise_celery
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://clausewise_user:clausewise_secure_password@postgres-db:5432/clausewise
      REDIS_URL: redis://:redis_secure_password@redis-broker:6379/0
      SECRET_KEY: your-super-secret-jwt-key-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      ENVIRONMENT: production
    volumes:
      - ./backend:/app
      - document_uploads:/app/uploads
    depends_on:
      - postgres-db
      - redis-broker
    restart: unless-stopped
    networks:
      - clausewise_network

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: clausewise_frontend
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend-api
    restart: unless-stopped
    networks:
      - clausewise_network

volumes:
  postgres_data:
  redis_data:
  document_uploads:

networks:
  clausewise_network:
    driver: bridge